# Generated by Django 4.2.3 on 2023-08-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPaggina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('camada', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=15)),
            ],
        ),
    ]
